### ISSUE TITLE
Mejoren los nombres de los tests

### ISSUE THREAD

**Issue by sanuzzi** [ccalvoromero/G11-K2002-2018#31]
Por ejemplo, tienen esto: "Nivel de hichizeria de Rolando con espectro malefico"

Eso no dice qué están testeando. Sería mejor si dijese "Si Rolando prefiere el Espectro Maléfico, entonces tiene X puntos". Y así.

Mejoren todos los nombres de los tests.

**Comment by LoreMalicki** [comment]
Algunos nombres siguen rancios
