### ISSUE TITLE
Inicialicen en el objeto y/o en el fixture. Eviten repetir en los tests

### ISSUE THREAD

**Issue by sanuzzi** [ccalvoromero/G11-K2002-2018#33]
En varios casos, por ejemplo, tienen esto:
rolando.setHechizoPreferido(espectroMalefico)

En vez de repetirlo varias veces, pueden dejarlo como hechizo preferido por defecto de Rolando:
var property hechizoPreferido = espectroMalefico

O bien, poner la inicialización en el fixture del test.

Otro ejemplo que repiten varias veces:
rolando.agregarArtefacto(espadaDelDestino)
rolando.agregarArtefacto(collarDivino)
rolando.agregarArtefacto(mascaraOscura)

Otro ejemplo, es que el objeto espectroMalefico se llame "Espectro maléfico". Se requiere eso casi siempre, déjenlo en el mismo objeto.

Y así tienen más casos. Revisen.

Una vez que dividan los tests en 3 archivos, vean esas repeticiones y evítenlas de la forma que más crean conveniente.

**Comment by LoreMalicki** [comment]
Ejemplo: úrsula, prieto, collardivino, etc. Revisar en todos los tests
